/* Generated by cbindgen. DO NOT EDIT BY HAND. */

#ifndef ACCRETA_FFI_H
#define ACCRETA_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status code returned by every fallible `accreta_*` function.
 *
 * `0` (`Ok`) always means success. Every other value is negative, so a caller who only checks
 * `status != 0` or `status < 0` both work. On any non-`Ok` status, call
 * [`accreta_last_error_message`] on the *same thread* for a human-readable description.
 */
enum AccretaStatus
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    ACCRETA_STATUS_OK = 0,
    /**
     * A required pointer argument was null.
     */
    ACCRETA_STATUS_NULL_POINTER = -1,
    /**
     * A `const char*` argument was not valid UTF-8.
     */
    ACCRETA_STATUS_INVALID_UTF8 = -2,
    /**
     * Schema construction failed (no dimension / no measure registered, or similar).
     */
    ACCRETA_STATUS_SCHEMA = -3,
    /**
     * `accreta_engine_ingest` rejected the sample (wrong measure count/type, wrong dimension
     * count).
     */
    ACCRETA_STATUS_INGEST = -4,
    /**
     * The requested item (bucket, measure id, aggregate kind for that measure, ...) does not
     * exist.
     */
    ACCRETA_STATUS_NOT_FOUND = -5,
    /**
     * A Rust panic was caught at the FFI boundary. The operation did not complete; the object it
     * was called on should be treated as unusable and freed.
     */
    ACCRETA_STATUS_PANIC = -6,
    /**
     * The requested [`crate::types::AccretaAggregateKind`] was not registered for that measure,
     * or the supplied [`crate::types::AccretaMeasureType`] didn't match the measure's actual
     * type.
     */
    ACCRETA_STATUS_TYPE_MISMATCH = -7,
    /**
     * A length/index argument was out of range or inconsistent (e.g. a measures array whose
     * length doesn't match what a subsequent call expects).
     */
    ACCRETA_STATUS_INVALID_ARGUMENT = -8,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AccretaStatus AccretaStatus;
#else
typedef int32_t AccretaStatus;
#endif // __STDC_VERSION__ >= 202311L

/**
 * The fixed set of built-in aggregate kinds this crate exposes across the C ABI.
 *
 * This intentionally does not (and cannot) grow to cover custom `Aggregator`/`Monoid`
 * implementations defined only in Rust — see the crate-level docs.
 */
enum AccretaAggregateKind
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    ACCRETA_AGGREGATE_KIND_SUM = 0,
    ACCRETA_AGGREGATE_KIND_COUNT = 1,
    ACCRETA_AGGREGATE_KIND_MIN = 2,
    ACCRETA_AGGREGATE_KIND_MAX = 3,
    ACCRETA_AGGREGATE_KIND_AVERAGE = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AccretaAggregateKind AccretaAggregateKind;
#else
typedef int32_t AccretaAggregateKind;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Mirrors [`accreta::measures::MeasureType`] — the numeric type of a measure's values.
 */
enum AccretaMeasureType
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    ACCRETA_MEASURE_TYPE_I64 = 0,
    ACCRETA_MEASURE_TYPE_U64 = 1,
    ACCRETA_MEASURE_TYPE_F64 = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AccretaMeasureType AccretaMeasureType;
#else
typedef int32_t AccretaMeasureType;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Mirrors [`accreta::bucket::BucketLevel`] — a granularity in the rollup hierarchy.
 */
enum AccretaBucketLevel
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    ACCRETA_BUCKET_LEVEL_MINUTE = 0,
    ACCRETA_BUCKET_LEVEL_HOUR = 1,
    ACCRETA_BUCKET_LEVEL_DAY = 2,
    ACCRETA_BUCKET_LEVEL_WEEK = 3,
    ACCRETA_BUCKET_LEVEL_MONTH = 4,
    ACCRETA_BUCKET_LEVEL_YEAR = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AccretaBucketLevel AccretaBucketLevel;
#else
typedef int32_t AccretaBucketLevel;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Opaque handle to an owned [`accreta::aggregate_set::AggregateSet`] — the states of every
 * aggregate attached to one measure, for one dimension group.
 *
 * Obtained from [`crate::accreta_engine_query_range`], a grouped-query cursor, or a bucket-group
 * cursor. Always owned by the caller; free it with [`accreta_aggregate_set_free`].
 */
typedef struct AccretaAggregateSet AccretaAggregateSet;

/**
 * Opaque handle to an owned list of [`AccretaAggregateSet`], one per measure in registration
 * order — what a single dimension group in a [`crate::AccretaBucket`] holds.
 */
typedef struct AccretaAggregateSetList AccretaAggregateSetList;

/**
 * Opaque handle to an owned, cloned [`accreta::bucket::Bucket`].
 *
 * Obtained from [`crate::accreta_engine_bucket`] or an [`AccretaBucketCursor`]. It's a snapshot
 * — independent of the [`crate::AccretaEngine`] it came from, so later ingestion or rollups on
 * that engine won't be reflected in a bucket handle you're already holding. Free with
 * [`accreta_bucket_free`].
 */
typedef struct AccretaBucket AccretaBucket;

/**
 * Opaque cursor over a snapshot of every bucket stored at one level, in chronological order.
 */
typedef struct AccretaBucketCursor AccretaBucketCursor;

/**
 * Opaque handle to an owned [`accreta::dimensions::DimensionKey`] — a concrete combination of
 * dimension values, as returned by bucket-group and grouped-query iteration.
 */
typedef struct AccretaDimensionKey AccretaDimensionKey;

/**
 * Opaque handle to an owned [`accreta::engine::Engine`].
 */
typedef struct AccretaEngine AccretaEngine;

/**
 * Opaque cursor over a snapshot of a [`AccretaBucket`]'s dimension groups.
 *
 * Cloned eagerly at construction time (see [`accreta_bucket_groups_cursor`]) rather than
 * borrowing the bucket, so it's safe to keep iterating even if you free the originating
 * `AccretaBucket` first.
 */
typedef struct AccretaGroupCursor AccretaGroupCursor;

/**
 * Opaque cursor over the result of [`accreta_engine_query_range_grouped`]: one
 * `(dimension key, aggregate set)` pair per distinct value of the projected `group_by` mask.
 */
typedef struct AccretaGroupedQueryCursor AccretaGroupedQueryCursor;

/**
 * Opaque handle to an owned [`accreta::retention::Retention`] policy.
 */
typedef struct AccretaRetention AccretaRetention;

/**
 * Opaque handle to a built, immutable [`accreta::aggregate_set::Schema`].
 *
 * Cheap to keep around: internally it's reference-counted, so [`accreta_engine_new`] clones it
 * rather than consuming your handle — free your `AccretaSchema*` with
 * [`accreta_schema_free`] whenever you're done with it, independently of any engines built from
 * it.
 */
typedef struct AccretaSchema AccretaSchema;

/**
 * Opaque handle to an in-progress [`accreta::aggregate_set::SchemaBuilder`].
 *
 * Build one with [`accreta_schema_builder_new`], add every dimension and measure, then finish
 * it with [`accreta_schema_builder_build`], which consumes it. If you abandon a builder without
 * calling `build`, free it with [`accreta_schema_builder_free`] instead.
 */
typedef struct AccretaSchemaBuilder AccretaSchemaBuilder;

/**
 * Untagged payload for [`AccretaMeasureValue`]. Read the field matching the struct's `tag`;
 * reading any other field is undefined behavior, same as a C union.
 */
typedef union {
    int64_t i64;
    uint64_t u64;
    double f64;
} AccretaMeasureValueData;

/**
 * A runtime-typed numeric value: either a raw measure input, or an extracted aggregate result.
 *
 * `tag` says which field of `value` is active. `Count`'s value is always `u64`; `Average`'s is
 * always `f64`; `Sum`/`Min`/`Max` match the measure's own [`AccretaMeasureType`].
 */
typedef struct {
    AccretaMeasureType tag;
    AccretaMeasureValueData value;
} AccretaMeasureValue;

/**
 * Reads the value of `kind` for `set` (whose owning measure has type `measure_type`) into
 * `*out_value`.
 *
 * Returns [`AccretaStatus::TypeMismatch`] if `kind` was never attached to this measure in the
 * schema (e.g. asking for `Average` on a measure only registered with `Sum` and `Count`), or if
 * `kind` is `Min`/`Max` and no sample has been folded into this state yet.
 */
AccretaStatus accreta_aggregate_set_get_value(const AccretaAggregateSet *set,
                                              AccretaAggregateKind kind,
                                              AccretaMeasureType measure_type,
                                              AccretaMeasureValue *out_value);

/**
 * Frees an aggregate-set handle.
 */
void accreta_aggregate_set_free(AccretaAggregateSet *set);

/**
 * The number of measures represented in `list` (one [`AccretaAggregateSet`] per measure, in
 * schema registration order).
 */
uintptr_t accreta_aggregate_set_list_len(const AccretaAggregateSetList *list);

/**
 * Returns the aggregate set for measure `measure_index` (its position in schema registration
 * order, i.e. `MeasureId(measure_index).index()`) as a new owned handle — free it with
 * [`accreta_aggregate_set_free`], independently of `list`.
 *
 * Returns null if `measure_index` is out of range.
 */
AccretaAggregateSet *accreta_aggregate_set_list_get(const AccretaAggregateSetList *list,
                                                    uintptr_t measure_index);

/**
 * Frees an aggregate-set list handle. Does not affect handles already obtained from
 * [`accreta_aggregate_set_list_get`] — those are independently owned and must be freed
 * separately via [`accreta_aggregate_set_free`].
 */
void accreta_aggregate_set_list_free(AccretaAggregateSetList *list);

/**
 * The granularity of `bucket`.
 */
AccretaBucketLevel accreta_bucket_level(const AccretaBucket *bucket);

/**
 * The inclusive start of `bucket`'s time window, in milliseconds since the Unix epoch (UTC).
 */
int64_t accreta_bucket_start_ms(const AccretaBucket *bucket);

/**
 * The exclusive end of `bucket`'s time window, in milliseconds since the Unix epoch (UTC).
 */
int64_t accreta_bucket_end_ms(const AccretaBucket *bucket);

/**
 * The number of distinct full-dimension groups in `bucket`.
 */
uintptr_t accreta_bucket_group_count(const AccretaBucket *bucket);

/**
 * Frees a bucket handle.
 */
void accreta_bucket_free(AccretaBucket *bucket);

/**
 * Creates a cursor over every dimension group in `bucket`, in unspecified order.
 *
 * Free it with [`accreta_group_cursor_free`] once done (whether or not you consumed every item).
 */
AccretaGroupCursor *accreta_bucket_groups_cursor(const AccretaBucket *bucket);

/**
 * Advances `cursor`, writing the next group's key and aggregate-set list to `*out_key` /
 * `*out_sets` (both newly owned — free them with [`accreta_dimension_key_free`] /
 * [`accreta_aggregate_set_list_free`]).
 *
 * Returns `true` and writes the pair, or returns `false` (leaving the out params untouched) once
 * the cursor is exhausted.
 */
bool accreta_group_cursor_next(AccretaGroupCursor *cursor,
                               AccretaDimensionKey **out_key,
                               AccretaAggregateSetList **out_sets);

/**
 * Frees a group cursor. Does not affect items already produced by [`accreta_group_cursor_next`]
 * — free those separately.
 */
void accreta_group_cursor_free(AccretaGroupCursor *cursor);

/**
 * The number of values in `key`.
 */
uintptr_t accreta_dimension_key_len(const AccretaDimensionKey *key);

/**
 * Reads the value at `index` into `*out_value`.
 *
 * Returns [`AccretaStatus::NotFound`] if `index` is out of range.
 */
AccretaStatus accreta_dimension_key_get(const AccretaDimensionKey *key,
                                        uintptr_t index,
                                        uint32_t *out_value);

/**
 * Frees a dimension key handle returned by a group or grouped-query cursor.
 */
void accreta_dimension_key_free(AccretaDimensionKey *key);

/**
 * Creates a retention policy that keeps every level forever (accreta's default).
 */
AccretaRetention *accreta_retention_new(void);

/**
 * Configures `retention` to keep buckets at `level` for at most `max_age_ms` past the newest
 * bucket currently stored at that level. Mutates `retention` in place.
 */
int32_t accreta_retention_keep(AccretaRetention *retention,
                               AccretaBucketLevel level,
                               int64_t max_age_ms);

/**
 * Frees a retention handle. Safe to free immediately after passing it to
 * [`accreta_engine_new_with_retention`] — the engine copies the policy (it's a small `Copy`
 * struct internally).
 */
void accreta_retention_free(AccretaRetention *retention);

/**
 * Creates a new engine tracking `schema`'s aggregates, with no retention limit. `schema` is
 * borrowed and cloned internally (cheap — it's reference-counted); free your `schema` handle
 * independently whenever you're done with it.
 */
AccretaEngine *accreta_engine_new(const AccretaSchema *schema);

/**
 * Like [`accreta_engine_new`], but discarding buckets per `retention` whenever
 * [`accreta_engine_prune`] is called.
 */
AccretaEngine *accreta_engine_new_with_retention(const AccretaSchema *schema,
                                                 const AccretaRetention *retention);

/**
 * Frees an engine handle. Does not affect any [`AccretaBucket`] / [`AccretaAggregateSet`]
 * snapshots you already pulled out of it — those are independently owned.
 */
void accreta_engine_free(AccretaEngine *engine);

/**
 * Folds one raw sample into `engine`'s minute bucket for `timestamp_ms`.
 *
 * `measures` (`measures_len` entries, in `MeasureId` order) and `dimensions` (`dimensions_len`
 * NUL-terminated UTF-8 strings, in `DimensionId` order) must each match the schema's counts —
 * see [`accreta_schema_measure_count`] / [`accreta_schema_dimension_count`]. Each measure
 * value's own `tag` determines how it's interpreted; if it doesn't match that measure's declared
 * type, accreta itself rejects the sample with [`AccretaStatus::Ingest`].
 */
int32_t accreta_engine_ingest(AccretaEngine *engine,
                              int64_t timestamp_ms,
                              const AccretaMeasureValue *measures,
                              uintptr_t measures_len,
                              const char *const *dimensions,
                              uintptr_t dimensions_len);

/**
 * Recomputes every level above `Minute` by merging bucket states upward. Safe to call
 * repeatedly.
 */
void accreta_engine_rollup(AccretaEngine *engine);

/**
 * Discards buckets older than `engine`'s configured [`AccretaRetention`] window, per level.
 */
void accreta_engine_prune(AccretaEngine *engine);

/**
 * Looks up the single bucket at `level` starting exactly at `start_ms` (already truncated to
 * `level` — see `BucketLevel::truncate` in the Rust docs), writing an owned snapshot to
 * `*out_bucket`.
 *
 * Returns [`AccretaStatus::NotFound`] (leaving `*out_bucket` untouched) if no such bucket exists.
 */
int32_t accreta_engine_bucket(const AccretaEngine *engine,
                              AccretaBucketLevel level,
                              int64_t start_ms,
                              AccretaBucket **out_bucket);

/**
 * How many buckets are currently stored at `level`.
 */
uintptr_t accreta_engine_bucket_count(const AccretaEngine *engine, AccretaBucketLevel level);

/**
 * Creates a cursor over every bucket currently stored at `level`. Free with
 * [`accreta_bucket_cursor_free`].
 */
AccretaBucketCursor *accreta_engine_buckets_cursor(const AccretaEngine *engine,
                                                   AccretaBucketLevel level);

/**
 * Advances `cursor`, writing the next bucket (owned) to `*out_bucket`. Returns `false` once
 * exhausted.
 */
bool accreta_bucket_cursor_next(AccretaBucketCursor *cursor, AccretaBucket **out_bucket);

/**
 * Frees a bucket cursor.
 */
void accreta_bucket_cursor_free(AccretaBucketCursor *cursor);

/**
 * Merges every bucket at `level` overlapping `[range_start_ms, range_end_ms)` into one total
 * [`AccretaAggregateSet`] for `measure_id`, across every dimension group — i.e. the ungrouped
 * total. Writes the owned result to `*out_set`.
 */
int32_t accreta_engine_query_range(const AccretaEngine *engine,
                                   AccretaBucketLevel level,
                                   int64_t range_start_ms,
                                   int64_t range_end_ms,
                                   uint8_t measure_id,
                                   AccretaAggregateSet **out_set);

/**
 * Like [`accreta_engine_query_range`], but grouped by the dimensions selected by `group_by_bits`
 * (bit `i` selects `DimensionId(i)`; `0` groups by nothing, producing one overall total). Writes
 * a cursor over the grouped results to `*out_cursor`.
 */
int32_t accreta_engine_query_range_grouped(const AccretaEngine *engine,
                                           AccretaBucketLevel level,
                                           int64_t range_start_ms,
                                           int64_t range_end_ms,
                                           uint8_t measure_id,
                                           uint64_t group_by_bits,
                                           AccretaGroupedQueryCursor **out_cursor);

/**
 * Advances `cursor`, writing the next `(key, set)` pair (both owned) to `*out_key` / `*out_set`.
 * Returns `false` once exhausted.
 */
bool accreta_grouped_query_cursor_next(AccretaGroupedQueryCursor *cursor,
                                       AccretaDimensionKey **out_key,
                                       AccretaAggregateSet **out_set);

/**
 * Frees a grouped-query cursor.
 */
void accreta_grouped_query_cursor_free(AccretaGroupedQueryCursor *cursor);

/**
 * The message associated with the most recent non-[`AccretaStatus::Ok`] status returned by a
 * call to this crate *on the calling thread*.
 *
 * The returned pointer is valid until the next `accreta_*` call on this thread, and must not be
 * freed by the caller. Returns null if no error has been recorded on this thread yet (or the
 * last error has since been superseded by a successful call).
 */
const char *accreta_last_error_message(void);

/**
 * Clears this thread's last-error message. Not required for correctness — every fallible call
 * either succeeds (leaving any prior message stale but harmless) or overwrites it — but useful
 * for tests or long-lived worker threads that want to assert no error occurred.
 */
void accreta_clear_last_error(void);

/**
 * Creates a new, empty schema builder.
 */
AccretaSchemaBuilder *accreta_schema_builder_new(void);

/**
 * Frees a builder that was never passed to [`accreta_schema_builder_build`].
 *
 * Do not call this on a builder that `build` already consumed — `build` frees it for you.
 */
void accreta_schema_builder_free(AccretaSchemaBuilder *builder);

/**
 * Registers a dimension named `name`. Registering the same name twice is a no-op, matching
 * [`accreta::aggregate_set::SchemaBuilder::dimension`].
 *
 * Returns [`AccretaStatus::Panic`] if more than 64 dimensions have already been registered (a
 * dimension mask can only represent 64 dimensions) — the builder should be discarded via
 * [`accreta_schema_builder_free`] after that.
 */
AccretaStatus accreta_schema_builder_add_dimension(AccretaSchemaBuilder *builder, const char *name);

/**
 * Registers a measure named `name` with numeric type `measure_type`, and attaches every
 * aggregate kind in `kinds` (`kinds_len` entries; pass `kinds = NULL, kinds_len = 0` for a
 * measure tracked by no built-in aggregate) to it in one call.
 *
 * This exists as a single call — rather than mirroring `SchemaBuilder::measure` returning a
 * separate builder handle — because `MeasureBuilder` borrows the `SchemaBuilder` it came from,
 * and that borrow can't be expressed as a second, independently-freed C handle.
 *
 * Returns [`AccretaStatus::Panic`] if `name` duplicates an already-registered measure, or if the
 * same aggregate kind appears more than once in `kinds` — both are program-logic errors on the
 * caller's part, matching the panics in the underlying Rust API.
 */
AccretaStatus accreta_schema_builder_add_measure(AccretaSchemaBuilder *builder,
                                                 const char *name,
                                                 AccretaMeasureType measure_type,
                                                 const AccretaAggregateKind *kinds,
                                                 uintptr_t kinds_len);

/**
 * Finishes building a schema, consuming and freeing `builder` either way.
 *
 * On success, `*out_schema` is set to a new [`AccretaSchema`] handle the caller owns (free it
 * with [`accreta_schema_free`]). On failure, `*out_schema` is set to null and a status
 * describing why (no dimension / no measure registered) is returned; see
 * [`accreta_last_error_message`].
 */
AccretaStatus accreta_schema_builder_build(AccretaSchemaBuilder *builder,
                                           AccretaSchema **out_schema);

/**
 * Frees a schema handle. Does not affect any [`AccretaEngine`](crate::AccretaEngine) already
 * built from it — engines hold their own clone.
 */
void accreta_schema_free(AccretaSchema *schema);

/**
 * The number of dimensions registered in `schema`.
 */
uintptr_t accreta_schema_dimension_count(const AccretaSchema *schema);

/**
 * The number of measures registered in `schema`.
 */
uintptr_t accreta_schema_measure_count(const AccretaSchema *schema);

/**
 * The numeric type of measure `measure_id`, written to `*out_type`.
 *
 * Returns [`AccretaStatus::NotFound`] if `measure_id` isn't registered in this schema.
 */
AccretaStatus accreta_schema_measure_type(const AccretaSchema *schema,
                                          uint8_t measure_id,
                                          AccretaMeasureType *out_type);

#endif  /* ACCRETA_FFI_H */
